"""Add new columns to User

Revision ID: 2e9a10b5d153
Revises: a071161e1109
Create Date: 2025-09-05 15:01:06.800752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e9a10b5d153'
down_revision: Union[str, Sequence[str], None] = 'a071161e1109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queries_queryId'), table_name='query')
    op.drop_table('queries')
    op.drop_index(op.f('ix_query_results_resultId'), table_name='query_result')
    op.drop_table('query_result')
    op.drop_index(op.f('ix_context_tables_contextId'), table_name='context_table')
    op.drop_table('context_table')
    op.drop_index(op.f('ix_analyses_analysisId'), table_name='analysis')
    op.drop_table('analysis')
    op.drop_index(op.f('ix_dashboards_dashboardId'), table_name='dashboard')
    op.drop_table('dashboard')
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    op.create_table('dashboards',
    sa.Column('dashboardId', sa.INTEGER(), server_default=sa.text('nextval(\'"dashboards_dashboardId_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('analysisId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['analysisId'], ['analyses.analysisId'], name='dashboards_analysisId_fkey'),
    sa.PrimaryKeyConstraint('dashboardId', name='dashboards_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_dashboards_dashboardId'), 'dashboards', ['dashboardId'], unique=False)
    op.create_table('analyses',
    sa.Column('analysisId', sa.INTEGER(), server_default=sa.text('nextval(\'"analyses_analysisId_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.user_id'], name='analyses_userId_fkey'),
    sa.PrimaryKeyConstraint('analysisId', name='analyses_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_analyses_analysisId'), 'analyses', ['analysisId'], unique=False)
    op.create_table('context_tables',
    sa.Column('contextId', sa.INTEGER(), server_default=sa.text('nextval(\'"context_tables_contextId_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('contextId', name='context_tables_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_context_tables_contextId'), 'context_tables', ['contextId'], unique=False)
    op.create_table('query_results',
    sa.Column('resultId', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('csvFileName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('chartType', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('queryId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['queryId'], ['queries.queryId'], name=op.f('query_results_queryId_fkey')),
    sa.PrimaryKeyConstraint('resultId', name=op.f('query_results_pkey'))
    )
    op.create_index(op.f('ix_query_results_resultId'), 'query_results', ['resultId'], unique=False)
    op.create_table('queries',
    sa.Column('queryId', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('queryStr', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contextId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('analysisId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dashboardId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['analysisId'], ['analysis.analysisId'], name=op.f('queries_analysisId_fkey')),
    sa.ForeignKeyConstraint(['contextId'], ['context_table.contextId'], name=op.f('queries_contextId_fkey')),
    sa.ForeignKeyConstraint(['dashboardId'], ['dashboard.dashboardId'], name=op.f('queries_dashboardId_fkey')),
    sa.PrimaryKeyConstraint('queryId', name=op.f('queries_pkey'))
    )
    op.create_index(op.f('ix_queries_queryId'), 'queries', ['queryId'], unique=False)
    # ### end Alembic commands ###
