# -*- coding: utf-8 -*-
"""8. Expense & Cost Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BhOjyBu-Xde-5vv1bT5LsqFzouxLV0Zz
"""

import pandas as pd
from datetime import datetime
import clickhouse_connect
import os

# --- Config ---
clickhouse_host = "57.159.27.80"
clickhouse_port = 8123
clickhouse_database = "fmac_db"
clickhouse_user = "fmacadmin"
clickhouse_password = "fmac*2025"

# --- Initialize Client ---
def initialize_clickhouse_client():
    """Initialize and return the ClickHouse client."""
    try:
        client = clickhouse_connect.get_client(
            host=clickhouse_host,
            port=clickhouse_port,
            username=clickhouse_user,
            password=clickhouse_password,
            database=clickhouse_database
        )
        print("ClickHouse client initialized successfully.")
        return client
    except Exception as e:
        print(f"Failed to initialize ClickHouse client: {e}")
        raise


# === Expense Analytics (8.1–8.7) ===
queries = [
    ("total_expenses_by_type", """
        SELECT
            SUM(legal_costs) AS total_legal,
            SUM(maintenance_preservation_costs) AS total_maintenance,
            SUM(taxes_insurance) AS total_taxes,
            SUM(misc_expenses) AS total_misc,
            SUM(expenses) AS total_other_expenses,
            SUM(legal_costs + maintenance_preservation_costs + taxes_insurance + misc_expenses + expenses) AS total_expenses
        FROM performance_updated_2025_ctas
    """, "What are the total expenses by category (legal, maintenance, taxes, etc.)?",
       "Expense type summary", "bar", "bar,pie,histogram"),

    ("avg_expense_per_resolved_loan", """
        SELECT
            AVG(legal_costs + maintenance_preservation_costs + taxes_insurance + misc_expenses + expenses) AS avg_expense_per_resolved_loan
        FROM performance_updated_2025_ctas
        WHERE zero_balance_code IS NOT NULL
    """, "What is the average total expense per resolved loan?",
       "Average expense per resolved loan", "single_value", "single_value"),

    ("monthly_expense_trend", """
        SELECT
            monthly_reporting_period,
            SUM(legal_costs + maintenance_preservation_costs + taxes_insurance + misc_expenses + expenses) AS total_expenses
        FROM performance_updated_2025_ctas
        GROUP BY monthly_reporting_period
        ORDER BY monthly_reporting_period
    """, "How do total expenses trend over time (monthly)?",
       "Monthly expense trend", "line", "line,scatter,bar"),

    ("expense_by_zero_balance_code", """
        SELECT
            zero_balance_code,
            SUM(legal_costs + maintenance_preservation_costs + taxes_insurance + misc_expenses + expenses) AS total_expense
        FROM performance_updated_2025_ctas
        WHERE zero_balance_code IS NOT NULL
        GROUP BY zero_balance_code
    """, "What is the distribution of expenses by resolution type (zero balance code)?",
       "Expense by resolution type", "bar", "bar,histogram,pie"),

    ("expense_per_upb", """
        SELECT
            SUM(legal_costs + maintenance_preservation_costs + taxes_insurance + misc_expenses + expenses) /
            NULLIF(SUM(current_actual_upb), 0) AS expense_per_upb
        FROM performance_updated_2025_ctas
    """, "What is the ratio of total expenses to total UPB?",
       "Expense-to-UPB ratio", "single_value", "single_value"),

    ("expense_breakdown_for_modified_loans", """
        SELECT
            modification_flag,
            SUM(legal_costs) AS legal_costs,
            SUM(maintenance_preservation_costs) AS maintenance_costs,
            SUM(taxes_insurance) AS taxes,
            SUM(misc_expenses) AS misc
        FROM performance_updated_2025_ctas
        GROUP BY modification_flag
    """, "How do expenses differ between modified and unmodified loans?",
       "Expense breakdown for modified vs. unmodified", "bar", "bar,scatter,line"),

    ("expense_vs_loss_efficiency", """
        SELECT
            DATE_TRUNC('month', zero_balance_effective_date) AS month,
            SUM(actual_loss) AS total_loss,
            SUM(legal_costs + maintenance_preservation_costs + taxes_insurance + misc_expenses + expenses) AS total_expense,
            SUM(actual_loss) /
            NULLIF(SUM(legal_costs + maintenance_preservation_costs + taxes_insurance + misc_expenses + expenses), 0) AS loss_to_expense_ratio
        FROM performance_updated_2025_ctas
        WHERE zero_balance_code IS NOT NULL
        GROUP BY month
        ORDER BY month
    """, "How does the loss-to-expense ratio trend monthly (efficiency)?",
       "Loss-to-expense efficiency", "line", "line,bar,histogram")
]


# === Generate Analytical Query Metadata ===
now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def run_expense_cost_analysis_queries():
    client = initialize_clickhouse_client()
    output_dir = "general_out_csvfiles"
    output_save_dir = "app/general_out_csvfiles"
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(output_save_dir, exist_ok=True)
    results = []
    for i, (name, sql, q_str, desc, chart, suggested_chart) in enumerate(queries, start=1):
        try:
            result = client.query(sql)
            result_df = pd.DataFrame(result.result_rows, columns=result.column_names)
            csv_filename = f"general_query_{i}_{name}.csv"
            csv_save_path = os.path.join(output_save_dir, csv_filename)
            result_df.to_csv(csv_save_path, index=False, encoding="utf-8")
            csv_table_path = os.path.join(output_dir, csv_filename)
            results.append({
                "query_sql_string": sql.strip(),
                "query_str": q_str,
                "description": desc,
                "csv_file_path": csv_table_path,
                "chart_type": chart,
                "suggested_chart_types": suggested_chart
            })
            print(f"Query {i} saved: {csv_save_path}")
        except Exception as e:
            print(f"Failed query {i}: {e}")
    client.close()
    return results