# -*- coding: utf-8 -*-
"""1.Loan Portfolio Overview

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YSHQnB1XVffC1LihxY569PlcZmKhL1Ip
"""

import pandas as pd
from datetime import datetime
import clickhouse_connect
import os

# --- Config ---
clickhouse_host = "57.159.27.80"
clickhouse_port = 8123
clickhouse_database = "fmac_db"
clickhouse_user = "fmacadmin"
clickhouse_password = "fmac*2025"

# --- Initialize Client ---
def initialize_clickhouse_client():
    """Initialize and return the ClickHouse client."""
    try:
        client = clickhouse_connect.get_client(
            host=clickhouse_host,
            port=clickhouse_port,
            username=clickhouse_user,
            password=clickhouse_password,
            database=clickhouse_database
        )
        print("ClickHouse client initialized successfully.")
        return client
    except Exception as e:
        print(f"❌ Failed to initialize ClickHouse client: {e}")
        raise


# === Analytical Queries (1.1–1.5) ===
queries = [
    ("total_loans_summary", """
        SELECT
            COUNT(DISTINCT loan_sequence_number) AS total_loans,
            SUM(current_actual_upb) AS total_upb,
            AVG(current_actual_upb) AS avg_upb,
            AVG(current_interest_rate) AS avg_interest_rate,
            AVG(loan_age) AS avg_loan_age
        FROM performance_updated_2025_ctas
        WHERE zero_balance_code IS NULL
    """, "What are the total loans, total & average UPB, average interest rate, and average loan age?",
       "Portfolio overview summary", "single_value", "single_value"),

    ("portfolio_distribution_by_rate_band", """
        SELECT
            CASE
                WHEN current_interest_rate < 3 THEN '<3%%'
                WHEN current_interest_rate BETWEEN 3 AND 5 THEN '3–5%%'
                WHEN current_interest_rate BETWEEN 5 AND 7 THEN '5–7%%'
                ELSE '>7%%'
            END AS rate_band,
            COUNT(*) AS loan_count,
            SUM(current_actual_upb) AS total_upb
        FROM performance_updated_2025_ctas
        GROUP BY rate_band
    """, "What is the portfolio distribution by interest rate bands?",
       "Rate band distribution", "bar", "bar,pie,histogram"),

    ("portfolio_distribution_by_upb_bucket", """
        SELECT
            CASE
                WHEN current_actual_upb < 100000 THEN '<100K'
                WHEN current_actual_upb BETWEEN 100000 AND 300000 THEN '100K–300K'
                WHEN current_actual_upb BETWEEN 300000 AND 600000 THEN '300K–600K'
                ELSE '>600K'
            END AS upb_bucket,
            COUNT(*) AS loan_count,
            SUM(current_actual_upb) AS total_upb
        FROM performance_updated_2025_ctas
        GROUP BY upb_bucket
    """, "What is the portfolio distribution by loan size (UPB buckets)?",
       "Loan size segmentation", "bar", "bar,scatter,pie"),

    ("loans_by_remaining_maturity", """
        SELECT
            CASE
                WHEN remaining_months_to_legal_maturity <= 60 THEN 'Short Term (<=5yrs)'
                WHEN remaining_months_to_legal_maturity BETWEEN 61 AND 180 THEN 'Medium Term (5–15yrs)'
                ELSE 'Long Term (>15yrs)'
            END AS maturity_bucket,
            COUNT(*) AS loan_count,
            SUM(current_actual_upb) AS total_upb
        FROM performance_updated_2025_ctas
        GROUP BY maturity_bucket
    """, "What is the count of loans by remaining maturity bucket?",
       "Remaining term segmentation", "bar", "bar,histogram,line"),

    ("loans_by_delinquency_status", """
        SELECT
            current_loan_delinquency_status,
            COUNT(*) AS loan_count,
            SUM(current_actual_upb) AS total_upb
        FROM performance_updated_2025_ctas
        GROUP BY current_loan_delinquency_status
        ORDER BY current_loan_delinquency_status
    """, "What is the count of loans by current delinquency status?",
       "Loan delinquency overview", "bar", "bar,pie,scatter")
]


# === Generate Analytical Query Metadata ===
now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def run_loan_portfolio_overview_queries():
    client = initialize_clickhouse_client()
    output_dir = "general_out_csvfiles"
    output_save_dir = "app/general_out_csvfiles"
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(output_save_dir, exist_ok=True)
    results = []
    for i, (name, sql, q_str, desc, chart, suggested_chart) in enumerate(queries, start=1):
        try:
            result = client.query(sql)
            result_df = pd.DataFrame(result.result_rows, columns=result.column_names)
            csv_filename = f"general_query_{i}_{name}.csv"
            csv_save_path = os.path.join(output_save_dir, csv_filename)
            result_df.to_csv(csv_save_path, index=False, encoding="utf-8")
            csv_table_path = os.path.join(output_dir, csv_filename)
            results.append({
                "query_sql_string": sql.strip(),
                "query_str": q_str,
                "description": desc,
                "csv_file_path": csv_table_path,
                "chart_type": chart,
                "suggested_chart_types": suggested_chart
            })
            print(f"Query {i} saved: {csv_save_path}")
        except Exception as e:
            print(f"Failed query {i}: {e}")
    client.close()
    return results