# -*- coding: utf-8 -*-
"""7. Risk & Exposure Analytics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zgd-8D2rSOdjLAnA9pORcxEX95q7iy24
"""

import pandas as pd
from datetime import datetime
import clickhouse_connect
import os

# --- Config ---
clickhouse_host = "57.159.27.80"
clickhouse_port = 8123
clickhouse_database = "fmac_db"
clickhouse_user = "fmacadmin"
clickhouse_password = "fmac*2025"

# --- Initialize Client ---
def initialize_clickhouse_client():
    """Initialize and return ClickHouse client."""
    try:
        client = clickhouse_connect.get_client(
            host=clickhouse_host,
            port=clickhouse_port,
            username=clickhouse_user,
            password=clickhouse_password,
            database=clickhouse_database
        )
        print("ClickHouse client initialized successfully.")
        return client
    except Exception as e:
        print(f"Failed to initialize ClickHouse client: {e}")
        raise


# === Risk & Exposure Analytics (7.1–7.7) ===
queries = [
    ("exposure_by_ltv_bucket", """
        SELECT
            CASE
                WHEN estimated_ltv < 80 THEN 'Low (<80%)'
                WHEN estimated_ltv BETWEEN 80 AND 95 THEN 'Medium (80–95%)'
                ELSE 'High (>95%)'
            END AS ltv_bucket,
            COUNT(*) AS loan_count,
            SUM(current_actual_upb) AS total_exposure,
            AVG(toInt8(current_loan_delinquency_status)) AS avg_delinquency
        FROM performance_updated_2025_ctas
        GROUP BY ltv_bucket
    """, "What is the portfolio exposure by LTV bucket (Low / Medium / High)?",
       "Exposure segmentation by LTV", "bar", "bar,pie,histogram"),

    ("exposure_by_delinquency_bucket", """
        SELECT
            CASE
                WHEN current_loan_delinquency_status = 0 THEN 'Current'
                WHEN current_loan_delinquency_status BETWEEN 1 AND 2 THEN '30 Days'
                WHEN current_loan_delinquency_status BETWEEN 3 AND 4 THEN '60 Days'
                WHEN current_loan_delinquency_status BETWEEN 5 AND 6 THEN '90 Days'
                ELSE '120+ Days'
            END AS delinquency_bucket,
            COUNT(*) AS loan_count,
            SUM(current_actual_upb) AS total_upb
        FROM performance_updated_2025_ctas
        GROUP BY delinquency_bucket
    """, "What is the total exposure by delinquency bucket?",
       "Delinquency bucket exposure", "bar", "bar,scatter,line"),

    ("high_risk_loans_exposure", """
        SELECT
            COUNT(*) AS high_risk_loans,
            SUM(current_actual_upb) AS exposure_upb
        FROM performance_updated_2025_ctas
        WHERE estimated_ltv > 90 AND current_loan_delinquency_status > 0
    """, "What is the count and UPB of high-risk loans (high LTV + delinquent)?",
       "High-risk exposure summary", "single_value", "single_value"),

    ("exposure_by_loan_age_bucket", """
        SELECT
            CASE
                WHEN loan_age < 12 THEN '0–1 Year'
                WHEN loan_age BETWEEN 12 AND 60 THEN '1–5 Years'
                ELSE '5+ Years'
            END AS age_bucket,
            COUNT(*) AS loan_count,
            SUM(current_actual_upb) AS total_upb
        FROM performance_updated_2025_ctas
        GROUP BY age_bucket
    """, "What is the exposure distribution by loan age bucket?",
       "Loan age exposure distribution", "bar", "bar,histogram,pie"),

    ("avg_upb_and_delinquency_by_ltv", """
        SELECT
            CASE
                WHEN estimated_ltv < 80 THEN '<80%'
                WHEN estimated_ltv BETWEEN 80 AND 95 THEN '80–95%'
                ELSE '>95%'
            END AS ltv_band,
            AVG(current_actual_upb) AS avg_upb,
            AVG(toInt8(current_loan_delinquency_status)) AS avg_delinquency
        FROM performance_updated_2025_ctas
        GROUP BY ltv_band
    """, "What are the average UPB and delinquency rate per LTV band?",
       "LTV vs UPB and delinquency", "bar", "bar,line,scatter"),

    ("top_10_loans_by_upb", """
        SELECT
            loan_sequence_number,
            current_actual_upb,
            estimated_ltv,
            current_loan_delinquency_status
        FROM performance_updated_2025_ctas
        ORDER BY current_actual_upb DESC
        LIMIT 10
    """, "Which are the top 10 loans by UPB (exposure concentration)?",
       "Top 10 exposure concentration", "bar", "bar,scatter,histogram"),

    ("exposure_by_modification_status", """
        SELECT
            modification_flag,
            COUNT(*) AS loan_count,
            SUM(current_actual_upb) AS total_upb,
            AVG(estimated_ltv) AS avg_ltv
        FROM performance_updated_2025_ctas
        GROUP BY modification_flag
    """, "What is the exposure distribution by modification status?",
       "Exposure by modification flag", "pie", "pie,bar,histogram")
]


# === Generate Analytical Query Metadata ===
now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def run_risk_exposure_analytics_queries():
    client = initialize_clickhouse_client()
    output_dir = "general_out_csvfiles"
    output_save_dir = "app/general_out_csvfiles"
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(output_save_dir, exist_ok=True)
    results = []
    for i, (name, sql, q_str, desc, chart, suggested_chart) in enumerate(queries, start=1):
        try:
            result = client.query(sql)
            result_df = pd.DataFrame(result.result_rows, columns=result.column_names)
            csv_filename = f"general_query_{i}_{name}.csv"
            csv_save_path = os.path.join(output_save_dir, csv_filename)
            result_df.to_csv(csv_save_path, index=False, encoding="utf-8")
            csv_table_path = os.path.join(output_dir, csv_filename)
            results.append({
                "query_sql_string": sql.strip(),
                "query_str": q_str,
                "description": desc,
                "csv_file_path": csv_table_path,
                "chart_type": chart,
                "suggested_chart_types": suggested_chart
            })
            print(f"Query {i} saved: {csv_save_path}")
        except Exception as e:
            print(f"Failed query {i}: {e}")
    client.close()
    return results