# -*- coding: utf-8 -*-
"""6. Time Series

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16NVLIJAlpvzc-KXc7rgH0oK9z0HE3EPX
"""

import pandas as pd
from datetime import datetime
import clickhouse_connect
import os

# --- Config ---
clickhouse_host = "57.159.27.80"
clickhouse_port = 8123
clickhouse_database = "fmac_db"
clickhouse_user = "fmacadmin"
clickhouse_password = "fmac*2025"

# --- Initialize Client ---
def initialize_clickhouse_client():
    """Initialize and return the ClickHouse client."""
    try:
        client = clickhouse_connect.get_client(
            host=clickhouse_host,
            port=clickhouse_port,
            username=clickhouse_user,
            password=clickhouse_password,
            database=clickhouse_database
        )
        print("ClickHouse client initialized successfully.")
        return client
    except Exception as e:
        print(f"Failed to initialize ClickHouse client: {e}")
        raise


# === Time Series Analytics Queries (6.x) ===
queries = [
    ("monthly_total_upb", """
        SELECT
            monthly_reporting_period,
            SUM(current_actual_upb) AS total_upb
        FROM performance_updated_2025_ctas
        GROUP BY monthly_reporting_period
        ORDER BY monthly_reporting_period
    """, "What is the total UPB by reporting month?",
       "Total UPB trend over time", "line", "line,scatter,bar"),

    ("avg_interest_rate_trend", """
        SELECT
            monthly_reporting_period,
            AVG(current_interest_rate) AS avg_interest_rate
        FROM performance_updated_2025_ctas
        GROUP BY monthly_reporting_period
        ORDER BY monthly_reporting_period
    """, "What is the trend in average interest rate by month?",
       "Average interest rate trend", "line", "line,bar,histogram"),

    ("monthly_delinquency_rate", """
        SELECT
            monthly_reporting_period,
            SUM(CASE WHEN current_loan_delinquency_status > 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS delinquency_rate
        FROM performance_updated_2025_ctas
        GROUP BY monthly_reporting_period
    """, "What is the monthly delinquency rate?",
       "Monthly delinquency rate", "line", "line,scatter,pie"),

    ("monthly_modifications", """
        SELECT
            monthly_reporting_period,
            COUNT(CASE WHEN modification_flag = 'Y' THEN 1 END) AS modifications,
            SUM(CASE WHEN modification_flag = 'Y' THEN current_actual_upb ELSE 0 END) AS modified_upb
        FROM performance_updated_2025_ctas
        GROUP BY monthly_reporting_period
    """, "What are the monthly counts and UPB of modified loans?",
       "Monthly loan modifications and UPB", "bar", "bar,histogram,line"),

    ("monthly_resolutions", """
        SELECT
            DATE_TRUNC('month', zero_balance_effective_date) AS month,
            COUNT(*) AS resolved_loans,
            SUM(zero_balance_removal_upb) AS resolved_upb
        FROM performance_updated_2025_ctas
        WHERE zero_balance_code IS NOT NULL
        GROUP BY month
    """, "What are the monthly resolutions (count and UPB)?",
       "Resolved loans and UPB by month", "bar", "bar,scatter,pie"),

    ("monthly_actual_loss_trend", """
        SELECT
            DATE_TRUNC('month', zero_balance_effective_date) AS month,
            SUM(actual_loss) AS total_loss
        FROM performance_updated_2025_ctas
        WHERE zero_balance_code IS NOT NULL
        GROUP BY month
    """, "What is the monthly actual loss trend?",
       "Monthly loss trend", "line", "line,bar,histogram"),

    ("monthly_expense_trend", """
        SELECT
            monthly_reporting_period,
            SUM(expenses + legal_costs + maintenance_preservation_costs + taxes_insurance + misc_expenses) AS total_expense
        FROM performance_updated_2025_ctas
        GROUP BY monthly_reporting_period
    """, "What is the monthly total expense trend?",
       "Monthly total expense trend", "line", "line,scatter,bar")
]


# === Generate Analytical Query Metadata ===
now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def run_time_series_queries():
    client = initialize_clickhouse_client()
    output_dir = "general_out_csvfiles"
    output_save_dir = "app/general_out_csvfiles"
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(output_save_dir, exist_ok=True)
    results = []
    for i, (name, sql, q_str, desc, chart, suggested_chart) in enumerate(queries, start=1):
        try:
            result = client.query(sql)
            result_df = pd.DataFrame(result.result_rows, columns=result.column_names)
            csv_filename = f"general_query_{i}_{name}.csv"
            csv_save_path = os.path.join(output_save_dir, csv_filename)
            result_df.to_csv(csv_save_path, index=False, encoding="utf-8")
            csv_table_path = os.path.join(output_dir, csv_filename)
            results.append({
                "query_sql_string": sql.strip(),
                "query_str": q_str,
                "description": desc,
                "csv_file_path": csv_table_path,
                "chart_type": chart,
                "suggested_chart_types": suggested_chart
            })
            print(f"Query {i} saved: {csv_save_path}")
        except Exception as e:
            print(f"Failed query {i}: {e}")
    client.close()
    return results