# -*- coding: utf-8 -*-
"""2. Delinquency Analytics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pe7WN6R_uhsTCWUllkoEaEu5u4wJfA62
"""

import pandas as pd
from datetime import datetime
import clickhouse_connect
import os

# --- Config ---
clickhouse_host = "57.159.27.80"
clickhouse_port = 8123
clickhouse_database = "fmac_db"
clickhouse_user = "fmacadmin"
clickhouse_password = "fmac*2025"


# --- Initialize Client ---
def initialize_clickhouse_client():
    """Initialize and return the ClickHouse client."""
    try:
        client = clickhouse_connect.get_client(
            host=clickhouse_host,
            port=clickhouse_port,
            username=clickhouse_user,
            password=clickhouse_password,
            database=clickhouse_database
        )
        print("ClickHouse client initialized successfully.")
        return client
    except Exception as e:
        print(f"Failed to initialize ClickHouse client: {e}")
        raise


# === Delinquency Analytics Queries (2.1–2.7) ===
queries = [
    ("total_delinquent_loans", """
        SELECT
            COUNT(*) AS delinquent_loans,
            COUNT(*) * 100.0 / (SELECT COUNT(*) FROM performance_updated_2025_ctas) AS delinquency_rate
        FROM performance_updated_2025_ctas
        WHERE current_loan_delinquency_status > 0
    """, "What is the total number and percentage of delinquent loans?",
       "Total delinquent loans summary", "single_value", "single_value"),

    ("delinquency_by_bucket", """
        SELECT
            CASE
                WHEN current_loan_delinquency_status BETWEEN 1 AND 2 THEN '30 Days'
                WHEN current_loan_delinquency_status BETWEEN 3 AND 4 THEN '60 Days'
                WHEN current_loan_delinquency_status BETWEEN 5 AND 6 THEN '90 Days'
                ELSE '120+ Days'
            END AS delinquency_bucket,
            COUNT(*) AS loan_count,
            SUM(current_actual_upb) AS upb
        FROM performance_updated_2025_ctas
        WHERE current_loan_delinquency_status > 0
        GROUP BY delinquency_bucket
    """, "What is the delinquency distribution by bucket (30/60/90/120+)?",
       "Delinquency bucket distribution", "bar", "bar,pie,histogram"),

    ("monthly_delinquency_trend", """
        SELECT
            monthly_reporting_period,
            SUM(CASE WHEN current_loan_delinquency_status > 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS delinquency_rate
        FROM performance_updated_2025_ctas
        GROUP BY monthly_reporting_period
        ORDER BY monthly_reporting_period
    """, "What is the monthly delinquency trend over time?",
       "Delinquency trend analysis", "line", "line,scatter,bar"),

    ("newly_delinquent_loans", """
        SELECT
            loan_sequence_number,
            monthly_reporting_period,
            current_loan_delinquency_status
        FROM performance_updated_2025_ctas
        WHERE current_loan_delinquency_status > 0
          AND loan_age = 1
    """, "Which loans became newly delinquent this month?",
       "Newly delinquent loan listing", "bar", "bar,histogram,pie"),


    ("avg_delinquent_upb", """
        SELECT
            AVG(current_actual_upb) AS avg_delinquent_upb
        FROM performance_updated_2025_ctas
        WHERE current_loan_delinquency_status > 0
    """, "What is the average UPB of delinquent loans?",
       "Average delinquent UPB", "single_value", "single_value"),

    ("delinquency_by_age_or_ltv", """
        SELECT
            CASE
                WHEN loan_age < 12 THEN '0–1 Year'
                WHEN loan_age BETWEEN 12 AND 60 THEN '1–5 Years'
                ELSE '5+ Years'
            END AS age_bucket,
            AVG(toInt8(current_loan_delinquency_status)) AS avg_delinquency,
            AVG(estimated_ltv) AS avg_ltv
        FROM performance_updated_2025_ctas
        GROUP BY age_bucket
    """, "How does delinquency vary by loan age and LTV?",
       "Delinquency by age or LTV", "bar", "bar,line,histogram")
]


# === Generate Analytical Query Metadata ===
now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def run_delinquency_analytics_queries():
    client = initialize_clickhouse_client()
    output_dir = "general_out_csvfiles"
    output_save_dir = "app/general_out_csvfiles"
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(output_save_dir, exist_ok=True)
    results = []
    for i, (name, sql, q_str, desc, chart, suggested_chart) in enumerate(queries, start=1):
        try:
            result = client.query(sql)
            result_df = pd.DataFrame(result.result_rows, columns=result.column_names)
            csv_filename = f"general_query_{i}_{name}.csv"
            csv_save_path = os.path.join(output_save_dir, csv_filename)
            result_df.to_csv(csv_save_path, index=False, encoding="utf-8")
            csv_table_path = os.path.join(output_dir, csv_filename)
            results.append({
                "query_sql_string": sql.strip(),
                "query_str": q_str,
                "description": desc,
                "csv_file_path": csv_table_path,
                "chart_type": chart,
                "suggested_chart_types": suggested_chart
            })
            print(f"Query {i} saved: {csv_save_path}")
        except Exception as e:
            print(f"Failed query {i}: {e}")
    client.close()
    return results