# -*- coding: utf-8 -*-
"""9.  Vintage Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a8kk6xso9-DopvaJR6Qn_r_WR0rsd0HK
"""

import pandas as pd
from datetime import datetime
import clickhouse_connect
import os

# --- Config ---
clickhouse_host = "57.159.27.80"
clickhouse_port = 8123
clickhouse_database = "fmac_db"
clickhouse_user = "fmacadmin"
clickhouse_password = "fmac*2025"

# --- Initialize Client ---
def initialize_clickhouse_client():
    """Initialize and return ClickHouse client."""
    try:
        client = clickhouse_connect.get_client(
            host=clickhouse_host,
            port=clickhouse_port,
            username=clickhouse_user,
            password=clickhouse_password,
            database=clickhouse_database
        )
        print("ClickHouse client initialized successfully.")
        return client
    except Exception as e:
        print(f"Failed to initialize ClickHouse client: {e}")
        raise


# === Vintage & Loan Age Analytics (9.1–9.7) ===
queries = [
    ("delinquency_rate_by_loan_age", """
        SELECT
            CASE
                WHEN loan_age < 12 THEN '0–1 Year'
                WHEN loan_age BETWEEN 12 AND 60 THEN '1–5 Years'
                ELSE '5+ Years'
            END AS age_bucket,
            SUM(CASE WHEN current_loan_delinquency_status > 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS delinquency_rate
        FROM performance_updated_2025_ctas
        GROUP BY age_bucket
    """, "What is the delinquency rate across different loan age buckets?",
       "Delinquency rate by loan age", "bar", "bar,pie,histogram"),

    ("loss_rate_by_vintage", """
        SELECT
            EXTRACT(YEAR FROM monthly_reporting_period) AS vintage_year,
            SUM(actual_loss) / NULLIF(SUM(zero_balance_removal_upb), 0) AS loss_rate
        FROM performance_updated_2025_ctas
        WHERE zero_balance_code IS NOT NULL
        GROUP BY vintage_year
    """, "What is the loss rate by loan vintage year?",
       "Loss rate by vintage", "bar", "bar,line,scatter"),

    ("avg_loan_age_and_upb_by_vintage", """
        SELECT
            EXTRACT(YEAR FROM monthly_reporting_period) AS vintage_year,
            AVG(loan_age) AS avg_loan_age,
            AVG(current_actual_upb) AS avg_upb
        FROM performance_updated_2025_ctas
        GROUP BY vintage_year
    """, "What are the average loan age and UPB across vintages?",
       "Average loan age and UPB by vintage", "bar", "bar,histogram,pie"),

    ("monthly_performance_by_vintage", """
        SELECT
            EXTRACT(YEAR FROM monthly_reporting_period) AS vintage_year,
            monthly_reporting_period,
            AVG(toInt8(current_loan_delinquency_status)) AS avg_delinquency
        FROM performance_updated_2025_ctas
        GROUP BY vintage_year, monthly_reporting_period
        ORDER BY vintage_year, monthly_reporting_period
    """, "How does delinquency evolve over time by vintage?",
       "Monthly performance by vintage", "line", "line,scatter,bar"),

    ("cumulative_default_rate_by_age", """
        SELECT
            loan_age,
            SUM(CASE WHEN current_loan_delinquency_status > 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS cumulative_default_rate
        FROM performance_updated_2025_ctas
        GROUP BY loan_age
        ORDER BY loan_age
    """, "What is the cumulative default rate as loans age?",
       "Cumulative default rate by loan age", "line", "line,bar,histogram"),

    ("recovery_rate_by_vintage", """
        SELECT
            EXTRACT(YEAR FROM zero_balance_effective_date) AS vintage_year,
            SUM(mi_recoveries + non_mi_recoveries) /
            NULLIF(SUM(actual_loss + mi_recoveries + non_mi_recoveries), 0) AS recovery_rate
        FROM performance_updated_2025_ctas
        WHERE zero_balance_code IS NOT NULL
        GROUP BY vintage_year
    """, "What is the recovery rate by loan vintage?",
       "Recovery rate by vintage", "single_value", "single_value"),

    ("modification_rate_by_vintage", """
        SELECT
            EXTRACT(YEAR FROM monthly_reporting_period) AS vintage_year,
            SUM(CASE WHEN modification_flag = 'Y' THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS modification_rate
        FROM performance_updated_2025_ctas
        GROUP BY vintage_year
    """, "How frequently do modifications occur by vintage?",
       "Modification rate by vintage", "bar", "bar,pie,scatter")
]


# === Generate Analytical Query Metadata ===
now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def run_vintage_analysis_queries():
    client = initialize_clickhouse_client()
    output_dir = "general_out_csvfiles"
    output_save_dir = "app/general_out_csvfiles"
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(output_save_dir, exist_ok=True)
    results = []
    for i, (name, sql, q_str, desc, chart, suggested_chart) in enumerate(queries, start=1):
        try:
            result = client.query(sql)
            result_df = pd.DataFrame(result.result_rows, columns=result.column_names)
            csv_filename = f"general_query_{i}_{name}.csv"
            csv_save_path = os.path.join(output_save_dir, csv_filename)
            result_df.to_csv(csv_save_path, index=False, encoding="utf-8")
            csv_table_path = os.path.join(output_dir, csv_filename)
            results.append({
                "query_sql_string": sql.strip(),
                "query_str": q_str,
                "description": desc,
                "csv_file_path": csv_table_path,
                "chart_type": chart,
                "suggested_chart_types": suggested_chart
            })
            print(f"Query {i} saved: {csv_save_path}")
        except Exception as e:
            print(f"Failed query {i}: {e}")
    client.close()
    return results