# -*- coding: utf-8 -*-
"""4. Loan Modification & Assistance

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pHktmtuWKXU_KdZS9KtvqZm4O4HgFrrn
"""


import pandas as pd
from datetime import datetime
import clickhouse_connect
import os

# --- Config ---
clickhouse_host = "57.159.27.80"
clickhouse_port = 8123
clickhouse_database = "fmac_db"
clickhouse_user = "fmacadmin"
clickhouse_password = "fmac*2025"


# --- Initialize Client ---
def initialize_clickhouse_client():
    """Initialize and return the ClickHouse client."""
    try:
        client = clickhouse_connect.get_client(
            host=clickhouse_host,
            port=clickhouse_port,
            username=clickhouse_user,
            password=clickhouse_password,
            database=clickhouse_database
        )
        print("ClickHouse client initialized successfully.")
        return client
    except Exception as e:
        print(f"Failed to initialize ClickHouse client: {e}")
        raise


# === Loan Modification Analytics Queries (4.1–4.7) ===
queries = [
    ("loan_modification_count", """
        SELECT
            modification_flag,
            COUNT(*) AS modified_loans
        FROM performance_updated_2025_ctas
        GROUP BY modification_flag
    """, "What is the total count of loans with modifications?",
       "Count of modified vs non-modified loans", "bar", "bar,pie,histogram"),

    ("deferred_upb_summary", """
        SELECT
            SUM(current_deferred_upb) AS total_deferred_upb,
            AVG(current_deferred_upb) AS avg_deferred_upb
        FROM performance_updated_2025_ctas
        WHERE modification_flag = 'Y'
    """, "What is the total and average deferred UPB for modified loans?",
       "Deferred UPB summary for modified loans", "single_value", "single_value"),

    ("step_modifications_count", """
        SELECT
            COUNT(*) AS step_mod_count
        FROM performance_updated_2025_ctas
        WHERE step_modification_flag = 'Y'
    """, "What is the total count of step modifications?",
       "Step modifications count", "single_value", "single_value"),

    ("borrower_assistance_summary", """
        SELECT
            borrower_assistance_status_code,
            COUNT(*) AS loan_count
        FROM performance_updated_2025_ctas
        GROUP BY borrower_assistance_status_code
    """, "What is the distribution of borrower assistance status codes?",
       "Borrower assistance summary", "bar", "bar,histogram,pie"),

    ("modification_trend_by_month", """
        SELECT
            monthly_reporting_period,
            SUM(CASE WHEN modification_flag = 'Y' THEN 1 ELSE 0 END) AS modified_loans
        FROM performance_updated_2025_ctas
        GROUP BY monthly_reporting_period
        ORDER BY monthly_reporting_period
    """, "What is the monthly trend of modified loans?",
       "Monthly modification trend", "line", "line,scatter,bar"),

    ("avg_modification_cost", """
        SELECT
            AVG(current_month_modification_cost) AS avg_modification_cost
        FROM performance_updated_2025_ctas
        WHERE modification_flag = 'Y'
    """, "What is the average modification cost per loan?",
       "Average modification cost", "single_value", "single_value"),

    ("delinquency_rate_after_modification", """
        SELECT
            modification_flag,
            AVG((current_loan_delinquency_status > 0)::FLOAT) * 100 AS delinquency_rate
        FROM performance_updated_2025_ctas
        GROUP BY modification_flag
    """, "What is the delinquency rate after loan modification?",
       "Delinquency rate after modification", "bar", "bar,line,scatter")
]


# === Generate Analytical Query Metadata ===
now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def run_loan_modification_assistance_queries():
    client = initialize_clickhouse_client()
    output_dir = "general_out_csvfiles"
    output_save_dir = "app/general_out_csvfiles"
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(output_save_dir, exist_ok=True)
    results = []
    for i, (name, sql, q_str, desc, chart, suggested_chart) in enumerate(queries, start=1):
        try:
            result = client.query(sql)
            result_df = pd.DataFrame(result.result_rows, columns=result.column_names)
            csv_filename = f"general_query_{i}_{name}.csv"
            csv_save_path = os.path.join(output_save_dir, csv_filename)
            result_df.to_csv(csv_save_path, index=False, encoding="utf-8")
            csv_table_path = os.path.join(output_dir, csv_filename)
            results.append({
                "query_sql_string": sql.strip(),
                "query_str": q_str,
                "description": desc,
                "csv_file_path": csv_table_path,
                "chart_type": chart,
                "suggested_chart_types": suggested_chart
            })
            print(f"Query {i} saved: {csv_save_path}")
        except Exception as e:
            print(f"Failed query {i}: {e}")
    client.close()
    return results