# -*- coding: utf-8 -*-
"""10. Custom Operational Metrics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jAH5XMNR9gmAwnyePtmfYLBC5X7tNQx0
"""

import pandas as pd
from datetime import datetime
import clickhouse_connect
import os

# --- Config ---
clickhouse_host = "57.159.27.80"
clickhouse_port = 8123
clickhouse_database = "fmac_db"
clickhouse_user = "fmacadmin"
clickhouse_password = "fmac*2025"

# --- Initialize Client ---
def initialize_clickhouse_client():
    """Initialize and return ClickHouse client."""
    try:
        client = clickhouse_connect.get_client(
            host=clickhouse_host,
            port=clickhouse_port,
            username=clickhouse_user,
            password=clickhouse_password,
            database=clickhouse_database
        )
        print("ClickHouse client initialized successfully.")
        return client
    except Exception as e:
        print(f"Failed to initialize ClickHouse client: {e}")
        raise


# === Special Metrics & Loan Characteristics (10.1–10.5) ===
queries = [
    ("avg_remaining_term", """
        SELECT AVG(remaining_months_to_legal_maturity) AS avg_remaining_term
        FROM performance_updated_2025_ctas
    """, "What is the average remaining term (months) to legal maturity?",
       "Average remaining term to maturity", "single_value", "single_value"),

    ("avg_interest_bearing_upb", """
        SELECT AVG(interest_bearing_upb) AS avg_interest_bearing_upb
        FROM performance_updated_2025_ctas
    """, "What is the average interest-bearing UPB across all active loans?",
       "Average interest-bearing UPB", "single_value", "single_value"),

    ("avg_current_month_mod_cost", """
        SELECT AVG(current_month_modification_cost) AS avg_mod_cost
        FROM performance_updated_2025_ctas
        WHERE current_month_modification_cost IS NOT NULL
    """, "What is the average modification cost recorded in the current month?",
       "Average monthly modification cost", "single_value", "single_value"),

    ("disaster_related_loans_count", """
        SELECT
            SUM(CASE WHEN delinquency_due_to_disaster = 'Y' THEN 1 ELSE 0 END) AS disaster_related_loans
        FROM performance_updated_2025_ctas
    """, "How many loans are currently flagged as disaster-related?",
       "Count of disaster-related loans", "single_value", "single_value"),

    ("delinquency_after_modification", """
        SELECT
            modification_flag,
            AVG(CASE WHEN current_loan_delinquency_status > 0 THEN 1 ELSE 0 END) * 100 AS delinquency_rate_after_mod
        FROM performance_updated_2025_ctas
        GROUP BY modification_flag
    """, "What is the delinquency rate among modified vs. unmodified loans?",
       "Delinquency rate after modification", "bar", "bar,pie,histogram")
]


# === Generate Analytical Query Metadata ===
now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def run_custom_operational_metrics_queries():
    client = initialize_clickhouse_client()
    output_dir = "general_out_csvfiles"
    output_save_dir = "app/general_out_csvfiles"
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(output_save_dir, exist_ok=True)
    results = []
    for i, (name, sql, q_str, desc, chart, suggested_chart) in enumerate(queries, start=1):
        try:
            result = client.query(sql)
            result_df = pd.DataFrame(result.result_rows, columns=result.column_names)
            csv_filename = f"general_query_{i}_{name}.csv"
            csv_save_path = os.path.join(output_save_dir, csv_filename)
            result_df.to_csv(csv_save_path, index=False, encoding="utf-8")
            csv_table_path = os.path.join(output_dir, csv_filename)
            results.append({
                "query_sql_string": sql.strip(),
                "query_str": q_str,
                "description": desc,
                "csv_file_path": csv_table_path,
                "chart_type": chart,
                "suggested_chart_types": suggested_chart
            })
            print(f"Query {i} saved: {csv_save_path}")
        except Exception as e:
            print(f"Failed query {i}: {e}")
    client.close()
    return results
