# -*- coding: utf-8 -*-
"""5. Zero Balance / Loan Resolution Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ERglRguUKC75UtapvULyGSWkat1gi4N
"""

import pandas as pd
from datetime import datetime
import clickhouse_connect
import os

# --- Config ---
clickhouse_host = "57.159.27.80"
clickhouse_port = 8123
clickhouse_database = "fmac_db"
clickhouse_user = "fmacadmin"
clickhouse_password = "fmac*2025"

# --- Initialize Client ---
def initialize_clickhouse_client():
    """Initialize and return the ClickHouse client."""
    try:
        client = clickhouse_connect.get_client(
            host=clickhouse_host,
            port=clickhouse_port,
            username=clickhouse_user,
            password=clickhouse_password,
            database=clickhouse_database
        )
        print("ClickHouse client initialized successfully.")
        return client
    except Exception as e:
        print(f"Failed to initialize ClickHouse client: {e}")
        raise


# === Zero Balance Analytics Queries (5.x) ===
queries = [
    ("loans_by_zero_balance_code", """
        SELECT
            zero_balance_code,
            COUNT(*) AS resolved_loans
        FROM performance_updated_2025_ctas
        WHERE zero_balance_code IS NOT NULL
        GROUP BY zero_balance_code
    """, "What is the count of loans by zero balance code?",
       "Resolved loan count by zero balance type", "bar", "bar,pie,histogram"),

    ("total_upb_by_zero_balance_code", """
        SELECT
            zero_balance_code,
            SUM(zero_balance_removal_upb) AS total_upb
        FROM performance_updated_2025_ctas
        WHERE zero_balance_code IS NOT NULL
        GROUP BY zero_balance_code
    """, "What is the total UPB by zero balance code?",
       "UPB distribution by resolution type", "bar", "bar,scatter,line"),

    ("resolution_trend_by_month", """
        SELECT
            DATE_TRUNC('month', zero_balance_effective_date) AS resolution_month,
            COUNT(*) AS resolved_loans
        FROM performance_updated_2025_ctas
        WHERE zero_balance_code IS NOT NULL
        GROUP BY resolution_month
        ORDER BY resolution_month
    """, "What is the monthly resolution trend for resolved loans?",
       "Monthly resolution trend", "line", "line,bar,scatter"),

    ("avg_loss_per_resolution_type", """
        SELECT
            zero_balance_code,
            AVG(actual_loss) AS avg_loss
        FROM performance_updated_2025_ctas
        WHERE zero_balance_code IS NOT NULL
        GROUP BY zero_balance_code
    """, "What is the average loss per resolution type?",
       "Average loss by zero balance type", "bar", "bar,histogram,pie"),

    ("resolved_loans_distribution_by_ltv", """
        SELECT
            CASE
                WHEN estimated_ltv < 80 THEN '<80%%'
                WHEN estimated_ltv BETWEEN 80 AND 95 THEN '80–95%%'
                ELSE '>95%%'
            END AS ltv_band,
            COUNT(*) AS loan_count
        FROM performance_updated_2025_ctas
        WHERE zero_balance_code IS NOT NULL
        GROUP BY ltv_band
    """, "What is the LTV distribution for resolved loans?",
       "Resolved loan distribution by LTV bands", "pie", "pie,bar,histogram"),

    ("monthly_resolution_rate", """
        SELECT
            monthly_reporting_period,
            SUM(CASE WHEN zero_balance_code IS NOT NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS resolution_rate
        FROM performance_updated_2025_ctas
        GROUP BY monthly_reporting_period
    """, "What is the monthly resolution rate across the portfolio?",
       "Monthly resolution rate trend", "line", "line,scatter,bar")
]


# === Generate Analytical Query Metadata ===
now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def run_zero_balance_loan_resolution_analysis_queries():
    client = initialize_clickhouse_client()
    output_dir = "general_out_csvfiles"
    output_save_dir = "app/general_out_csvfiles"
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(output_save_dir, exist_ok=True)
    results = []
    for i, (name, sql, q_str, desc, chart, suggested_chart) in enumerate(queries, start=1):
        try:
            result = client.query(sql)
            result_df = pd.DataFrame(result.result_rows, columns=result.column_names)
            csv_filename = f"general_query_{i}_{name}.csv"
            csv_save_path = os.path.join(output_save_dir, csv_filename)
            result_df.to_csv(csv_save_path, index=False, encoding="utf-8")
            csv_table_path = os.path.join(output_dir, csv_filename)
            results.append({
                "query_sql_string": sql.strip(),
                "query_str": q_str,
                "description": desc,
                "csv_file_path": csv_table_path,
                "chart_type": chart,
                "suggested_chart_types": suggested_chart
            })
            print(f"Query {i} saved: {csv_save_path}")
        except Exception as e:
            print(f"Failed query {i}: {e}")
    client.close()
    return results